name 'drewstinnett-systemd'
version '0.1.0'
source 'git://github.com/drewstinnett/puppet-systemd.git'
author 'Drew Stinnett'
description 'Puppet module for managing systemd'
summary 'Puppet module for managing systemd'
license 'MIT'
project_page 'https://github.com/drewstinnett/puppet-systemd'

dependency 'puppetlabs/inifile', '1.x'
dependency 'puppetlabs/stdlib', '>= 2.2.0'
